language: node_js
node_js:
  - 12
install:
  - npm install -g codecov
  - npm install -g jest
  - npm install jquery
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION